language: java
jobs:
  include:
    - os: linux
      dist: bionic
      jdk: openjdk11
    - os: linux
      dist: bionic
      jdk: oraclejdk11
    - os: linux
      dist: bionic
      jdk: openjdk8
    - os: linux
      dist: xenial
      jdk: openjdk8
#        - oraclejdk8
#jdk:
#  - openjdk11
#  - oraclejdk11
#  - openjdk8
#  - oraclejdk8
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
