language: java
os: linux
dist: xenial
jdk:
  - openjdk11
  - oraclejdk11
  - openjdk8
  - oraclejdk8
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
