language: java
jobs:
  include:
    - os: linux
      dist: bionic
      jdk: openjdk11
    - os: linux
      dist: bionic
      jdk: oraclejdk11
    - os: linux
      dist: xenial
      jdk: openjdk8
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
