language: java
services:
  - xvfb
jobs:
  include:
    # base code/ desktop app in jdk 11/8
    - os: linux
      dist: bionic
      jdk: openjdk11
      script:
        - ./gradlew check --stacktrace
        - ./gradlew codeCoverageReport
    - os: linux
      dist: bionic
      jdk: oraclejdk11
      script:
        - ./gradlew check --stacktrace
        - ./gradlew codeCoverageReport
    - os: linux
      dist: xenial
      jdk: openjdk8
      script:
        - ./gradlew check --stacktrace
        - ./gradlew codeCoverageReport
    # webserver native tests with graal
    # https://sormuras.github.io/blog/2018-06-22-jdk-matrix.html
    - os: linux
      dist: bionic
      env: JDK=graalvm-ce-19.2.1
      before_script:
        - unset -v _JAVA_OPTIONS
        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
      script:
        - source install-jdk.sh --url https://github.com/oracle/graal/releases/download/vm-19.2.1/graalvm-ce-linux-amd64-19.2.1.tar.gz # https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.0/graalvm-ce-java11-linux-amd64-19.3.0.tar.gz
        - java -version
        - ./gradlew WebServer:Server:check --stacktrace
        # TODO:: do native compile, check
        - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -f build/reports/jacoco/report.xml
after_failure:
  - find ./ -type f -iname "*.log" | xargs tail -n +1